version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:17.0-alpine3.19
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Rust Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      JWT_SECRET: hello
      PORT: 8000
      JWT_SECRET: hesoyam
      RUN_MIGRATIONS: true
      RUST_BACKTRACE: 1
    ports:
      - "8080:8080"

volumes:
  postgres_data:
