//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod saldo;
pub mod topups;
pub mod transfers;
pub mod users;
pub mod withdraws;


pub use users::Entity as Users;
pub use saldo::Entity as Saldo;
pub use transfers::Entity as Transfer;
pub use topups::Entity as Topup;
pub use withdraws::Entity as Withdraws;

