//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::saldo::Entity as Saldo;
pub use super::topups::Entity as Topups;
pub use super::transfers::Entity as Transfers;
pub use super::users::Entity as Users;
pub use super::withdraws::Entity as Withdraws;
